name: Go CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    name: Build, Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'
          cache: true
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: |
          go mod download
          go install go.uber.org/mock/mockgen@latest
          # Устанавливаем конкретную версию golangci-lint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.0

      - name: Generate mocks
        run: go generate ./...

      - name: Verify build
        run: GOOS=linux CGO_ENABLED=0 go build -v -o ./bin/app ./cmd/main.go

      - name: Run tests
        run: go test -race -cover ./...

      - name: Run linter
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run --timeout=5m
